version: '3'

services:
  web:
    build: .
    command: uvicorn main:app --reload --port=8000 --host=0.0.0.0 --workers 4
    env_file:
      - .env.dev
    ports:
      - 8000:8000
    volumes:
      - .:/app

